### ISSUE TITLE
Libexecdir move breaks package

### ISSUE THREAD

**Issue by gmbr3** [yast/yast-control-center#47]
%{_libexecdir} will be moving to /usr/libexec because of FHS 3.0. /usr/lib/YaST2/bin/y2controlcenter is affected

**Comment by dgdavid** [comment]
More information at https://en.opensuse.org/openSUSE:Specfile_guidelines#Libexecdir

> openSUSE Factory is in the process of changing <code>%_libexecdir</code> to <code>/usr/libexec</code> to match [Filesystem Hierarchy Standard](https://wiki.linuxfoundation.org/lsb/fhs) 3.0. Any packages which require a macro for <code>/usr/lib</code> are being changed to use <code>%_prefix/lib</code>. **openSUSE Leap 15.2 will still expand <code>%_libexecdir</code> to <code>/usr/lib</code>**

**Comment by gmbr3** [comment]
>> #48

**Comment by dgdavid** [comment]
@gmbr3 thanks a lot for the contribution and sorry for the delay. 

As you can see, @ancorgs managed to take care of it today and changes are already merged (#48 and #49)
